//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gssManRegistration.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gssManRegistrationDbContext : DbContext
    {
        public gssManRegistrationDbContext()
            : base("name=gssManRegistrationDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<branches> branches { get; set; }
        public virtual DbSet<registrations> registrations { get; set; }
        public virtual DbSet<tbl_student> tbl_student { get; set; }
        public virtual DbSet<tbl_studentages> tbl_studentages { get; set; }
        public virtual DbSet<tbl_studentdetail> tbl_studentdetail { get; set; }
        public virtual DbSet<tbl_studentexdetail> tbl_studentexdetail { get; set; }
        public virtual DbSet<tbl_studentexdetailmore> tbl_studentexdetailmore { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<userdetail> userdetail { get; set; }
    }
}
