//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gssManRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registrations
    {
        public long id { get; set; }
        public string regid { get; set; }
        public string studentid { get; set; }
        public string branch { get; set; }
        public string grade { get; set; }
        public string section { get; set; }
        public string academicyear { get; set; }
        public string regdate { get; set; }
        public string tag { get; set; }
    }
}
