//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gssManRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student
    {
        public long id { get; set; }
        public string currentenrolledyear { get; set; }
        public string studentid { get; set; }
        public string enrolleddate { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public string dob { get; set; }
        public string fathersname { get; set; }
        public string mothersname { get; set; }
        public string branch { get; set; }
        public string grade { get; set; }
        public string section { get; set; }
        public string gender { get; set; }
    }
}
