//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gssManRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_studentexdetailmore
    {
        public long id { get; set; }
        public string studentid { get; set; }
        public string kifleketema { get; set; }
        public string woreda { get; set; }
        public string housenumber { get; set; }
        public string countryofbirth { get; set; }
        public string passportnationality { get; set; }
        public string plid { get; set; }
        public string gohomealone { get; set; }
        public string fatherworkplace { get; set; }
        public string fathercity { get; set; }
        public string fatherofficenumber { get; set; }
        public string fatheremailaddress { get; set; }
        public string motherworkplace { get; set; }
        public string mothercity { get; set; }
        public string motherofficenumber { get; set; }
        public string motheremailaddress { get; set; }
        public string emergencyrelationship { get; set; }
        public string pickuprelationship { get; set; }
        public string emailaddress { get; set; }
    }
}
