//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gssManRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_studentages
    {
        public long id { get; set; }
        public string studentid { get; set; }
        public string age { get; set; }
        public string dobday { get; set; }
        public string dobmoth { get; set; }
        public string dobyear { get; set; }
    }
}
