//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gssManRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_studentexdetail
    {
        public long id { get; set; }
        public string studentid { get; set; }
        public string emergencycontactname { get; set; }
        public string emergencycontactnumber { get; set; }
        public string guardianname { get; set; }
        public string guardiannumber { get; set; }
        public string pickuppersonname { get; set; }
        public string pickuppersonnumber { get; set; }
    }
}
