//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gssManRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userdetail
    {
        public long id { get; set; }
        public string userid { get; set; }
        public string username { get; set; }
        public string usertype { get; set; }
        public string passwordchangedon { get; set; }
        public string lastseenon { get; set; }
        public string passwordchangefrequency { get; set; }
        public string accountstatus { get; set; }
        public string tag { get; set; }
    }
}
