//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gssManRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class weeklymarks20212022
    {
        public long id { get; set; }
        public string markid { get; set; }
        public string studentid { get; set; }
        public string weeknumber { get; set; }
        public string quarternumber { get; set; }
        public string acyear { get; set; }
        public string subjectid { get; set; }
        public string subjectname { get; set; }
        public string dateadded { get; set; }
        public string dateupdated { get; set; }
        public string description { get; set; }
        public string markvalue { get; set; }
        public string addedbyuserid { get; set; }
        public string updatedbyuserid { get; set; }
        public string flagged { get; set; }
        public string outofpoints { get; set; }
        public string quizorhomework { get; set; }
    }
}
